apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        name: flask-app
    spec:
      containers:
        - name: flask-app
          imagePullPolicy: Always
          image: 299522382061.dkr.ecr.ap-northeast-3.amazonaws.com/test-flask:test2
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
